#!/bin/sh

# Start hotkey daemon
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	3	
bspc config focused_border_color		'#8E8BD8'
bspc config normal_border_color		"#5C5C5C"
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#autostart

# Start notification daemon
dunst &
# Set wallpaper
feh --bg-fill /home/$USER/pics/wallpapers/0219.jpg
# Start compositor
picom &
# Start power manager
xfce4-power-manager &
# Set window manager name to fix broken Java programs
wmname LG3D &
# Set keyboard layout with shortcut
setxkbmap -layout us,fr
setxkbmap -option 'grp:alt_shift_toggle'
# Launch Polybar
$HOME/.config/polybar/launch.sh
